export const EVENTS = {
  ROOM_JOIN: 'room:join',
  ROOM_LEAVE: 'room:leave',
  ROOM_JOINED: 'room:joined',
  PRESENCE_LIST: 'presence:list',
  PRESENCE_JOINED: 'presence:joined',
  PRESENCE_LEFT: 'presence:left',
  CRDT_SYNC_STEP1: 'crdt:sync-step1',
  CRDT_SYNC_STEP2: 'crdt:sync-step2',
  CRDT_UPDATE: 'crdt:update',
  CRDT_AWARENESS: 'crdt:awareness',
  EXECUTION_RUN: 'execution:run',
  EXECUTION_STARTED: 'execution:started',
  EXECUTION_RESULT: 'execution:result',
  CHAT_MESSAGE: 'chat:message',
  CHAT_HISTORY: 'chat:history',
  ERROR: 'error',
};
